version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0
  node: circleci/node@5.0.2
  heroku: circleci/heroku@0.0.10

jobs:
  push-to-staging:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: markmcdapp133
      - run:
          name: Migrate 
          command: heroku run rake db:migrate --app markmcdapp133
      - run:
          name: Seed 
          command: heroku run rake seed:prod --app markmcdapp133
  push-to-prod:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: markmcdapp131
      - run:
          name: Migrate 
          command: heroku run rake db:migrate --app markmcdapp131
      - run:
          name: Seed 
          command: heroku run rake seed:prod --app markmcdapp131
  build-and-test:
    docker:
      - image: 'cimg/ruby:3.0.0-node'
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install NPM Globals
          command: sudo yarn global add sass gulp-cli
      - run:
          name: Transpiling JavaScript
          command: gulp scripts
      - run:
          name: Running Bundle Install
          command: bundle install

workflows:
  test_and_stage:
    jobs:
      - build-and-test
      - push-to-staging:
          requires:
            - build-and-test
          filters:
            branches:
              only: 
                - staging
  ship_to_prod:
    jobs:
      - push-to-prod:
          filters:
            branches:
              only: 
                - main