version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  stage:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: markmcdapp133
      - run:
          name: Migrate 
          command: heroku run rake db:migrate --app markmcdapp133
      - run:
          name: Seed 
          command: heroku run rake seed:prod --app markmcdapp133
workflows:
  stage_test_deploy:
    jobs:
      - stage